on:
  push:
  pull_request:
    branches:
      - main
      - master

name: build-deploy-book

env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  MINICONDA_LIB_PATH: /Users/runner/Library/r-miniconda/

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}

      - name: Cache renv packages
        uses: actions/cache@v2
        with:
          path:  ${{ env.RENV_PATHS_ROOT }}
          key: r-${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install TensorFlow
        run: |
          R -e 'install.packages("tensorflow")'
          R -e 'tensorflow::install_tensorflow(envname = "tensorflow")'

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Build book
        run: make gitbook

      - name: Checkout the gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: book-output

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: _book
